name: Go Lint
description: "Run go linter"
inputs:
  go-version:
    description: "GO version to use"
    required: false
    default: "1.21"

  golangci-lint-version:
    description: "golangci-lint version to use"
    required: false
    default: "v1.52.2"

  working-directory:
    description: "Working directory"
    required: false
    default: "."

  flags:
    description: "Linter flags"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup GO
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Clean existing cache directory
      shell: bash
      run: |
        if [ -d ~/.cache/golangci-lint ]; then
          echo "Cleaning existing golangci-lint cache directory..."
          rm -rf ~/.cache/golangci-lint
        fi

    - name: Cache golangci-lint
      uses: actions/cache@v3
      with:
        path: ~/.cache/golangci-lint
        key: golangci-lint-cache-${{ runner.os }}-${{ inputs.golangci-lint-version }}-${{ hashFiles('**/*.go', '**/go.sum', '**/go.mod') }}
        restore-keys: |
          golangci-lint-cache-${{ runner.os }}-${{ inputs.golangci-lint-version }}-
          golangci-lint-cache-${{ runner.os }}-

    - name: Install golangci-lint
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ inputs.golangci-lint-version }}

    - name: Run golangci-lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: golangci-lint run -v ${{ inputs.flags }}
