name: "GO Testing"
description: "Run tests and linting for GO applications"
inputs:
  go-version:
    description: "GO version to use"
    required: false
    default: "1.21"
  working-directory:
    description: "Working directory"
    required: false
    default: "."
  flags:
    description: "Testing Flags"
    required: false
    default: "-v"

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup GO
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}

    - name: Download deps
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: go mod download

    - name: Run Test
      shell: bash
      run: go test ./... ${{ inputs.flags }}
